//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coopera.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoopEntities : DbContext
    {
        public CoopEntities()
            : base("name=CoopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commandes> Commandes { get; set; }
        public virtual DbSet<Details_commande> Details_commande { get; set; }
        public virtual DbSet<Filliers> Filliers { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Produits> Produits { get; set; }
        public virtual DbSet<reviews> reviews { get; set; }
        public virtual DbSet<secteurDactivite> secteurDactivite { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
