//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coopera.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int UsersId { get; set; }
        public int ProduitsId { get; set; }
        public string Content { get; set; }
        public float Rating { get; set; }
    
        public virtual Produits Produits { get; set; }
        public virtual Users Users { get; set; }
    }
}
